import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "India Stock",
  description: "Generated by india stock ltd",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}
